# Generated by Django 3.2.8 on 2023-03-04 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_openid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='openid',
        ),
    ]
